/* eslint-disable no-restricted-globals */

import { clientsClaim } from 'workbox-core';
import { ExpirationPlugin } from 'workbox-expiration';
import { precacheAndRoute, createHandlerBoundToURL } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { StaleWhileRevalidate } from 'workbox-strategies';

clientsClaim();

// Precache static assets generated by the build
precacheAndRoute(self.__WB_MANIFEST);

// App-shell routing for SPA
const fileExtensionRegexp = new RegExp('/[^/?]+\\.[^/]+$');
registerRoute(
  ({ request, url }) => {
    if (request.mode !== 'navigate') return false;
    if (url.pathname.startsWith('/_')) return false;
    if (url.pathname.match(fileExtensionRegexp)) return false;
    return true;
  },
  createHandlerBoundToURL(process.env.PUBLIC_URL + '/index.html')
);

// Cache same-origin .png images (e.g., from public/)
registerRoute(
  ({ url }) => url.origin === self.location.origin && url.pathname.endsWith('.png'),
  new StaleWhileRevalidate({
    cacheName: 'images',
    plugins: [
      new ExpirationPlugin({ maxEntries: 50 }),
    ],
  })
);

// Constants
const S3_ORIGIN = 'https://icon-path-bucket.s3.us-east-2.amazonaws.com';
const S3_IMAGE_CACHE = 'product-images-v1';

// Allow skipWaiting trigger
self.addEventListener('message', (event) => {
  if (event.data?.type === 'SKIP_WAITING') {
    console.log('[SW] Skipping waiting...');
    self.skipWaiting();
  }
});

// Custom runtime caching for external S3-hosted images
self.addEventListener('fetch', (event) => {
  const { request } = event;
  const requestURL = new URL(request.url);

  const isS3Image = request.destination === 'image' && requestURL.origin === S3_ORIGIN;

  if (isS3Image) {
    event.respondWith(
      caches.open(S3_IMAGE_CACHE).then(async (cache) => {
        const cached = await cache.match(request);
        if (cached) {
          console.log('[SW] Serving from cache:', request.url);
          return cached;
        }

        try {
          const response = await fetch(request, { mode: 'cors' });
          // console.log("response:", response)
          if (response.ok && response.type === 'cors') {
            console.log('[SW] Caching new S3 image:', request.url);
            cache.put(request, response.clone());
          } else {
            console.warn('[SW] Not caching response:', request.url, response.status);
          }
          return response;
        } catch (err) {
          console.error('[SW] Fetch failed:', request.url, err);
          return fetch(request); // fallback
        }
      })
    );
  }
});


self.addEventListener('install', (event) => {
  console.log('[SW] Installing...');

  event.waitUntil(
    (async () => {
      const testImageURL = `https://icon-path-bucket.s3.us-east-2.amazonaws.com/660159fcb99e02f029328480-1741468743028-Jcodes (1).png`; 
      try {
        const cache = await caches.open(S3_IMAGE_CACHE);
        const response = await fetch(testImageURL, { mode: 'cors' });
        if (response.ok) {
          await cache.put(testImageURL, response.clone());
          console.log('[SW] Manually cached test image:', testImageURL);
        } else {
          console.warn('[SW] Test image fetch failed with status:', response.status);
        }
      } catch (e) {
        console.error('[SW] Failed to cache test image:', e);
      }
    })()
  );
});
